using FluentAssertions;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using PhenX.EntityFrameworkCore.BulkInsert.Abstractions;
using PhenX.EntityFrameworkCore.BulkInsert.Metadata;
using PhenX.EntityFrameworkCore.BulkInsert.Options;
using PhenX.EntityFrameworkCore.BulkInsert.Oracle;
using PhenX.EntityFrameworkCore.BulkInsert.Tests.DbContext;

using Xunit;

namespace PhenX.EntityFrameworkCore.BulkInsert.Tests.Tests.Merge;

/// <summary>
/// Container-free unit tests asserting the SQL generated by the Oracle dialect. These guard against
/// regressions that only surface against a live Oracle instance, such as ORA-03048 caused by a
/// trailing statement terminator on a plain (non PL/SQL) statement.
/// </summary>
[Trait("Category", "Oracle")]
public class OracleMergeSqlTests
{
    private static TestDbContextOracle CreateContext() => new()
    {
        ConfigureOptions = options => options
            .UseOracle("Data Source=dummy;User Id=u;Password=p;")
            .UseBulkInsertOracle()
    };

    [Fact]
    public void BuildMoveDataSql_ConflictUpdate_DoesNotEndWithStatementTerminator()
    {
        using var context = CreateContext();

        var provider = context.GetService<IBulkInsertProvider>();
        var tableInfo = new MetadataProvider().GetTableInfo<TestEntity>(context);
        var insertedColumns = tableInfo.GetColumns(includeGenerated: false);

        var onConflict = new OnConflictOptions<TestEntity>
        {
            Match = e => new { e.Name },
            Update = (inserted, excluded) => new TestEntity { Price = excluded.Price },
        };

        var sql = provider.SqlDialect.BuildMoveDataSql<TestEntity>(
            context,
            tableInfo,
            "source_temp",
            insertedColumns,
            [],
            new OracleBulkInsertOptions(),
            onConflict);

        sql.Should().Contain("MERGE INTO");
        sql.TrimEnd().Should().NotEndWith(";");
    }

    [Fact]
    public void BuildMoveDataSql_ConflictUpdateWithWhere_UsesTrailingWhereNotWhenMatchedAnd()
    {
        using var context = CreateContext();

        var provider = context.GetService<IBulkInsertProvider>();
        var tableInfo = new MetadataProvider().GetTableInfo<TestEntity>(context);
        var insertedColumns = tableInfo.GetColumns(includeGenerated: false);

        var onConflict = new OnConflictOptions<TestEntity>
        {
            Match = e => new { e.Name },
            Update = (inserted, excluded) => new TestEntity { Price = excluded.Price },
            // A conditional update: Oracle expresses this as a trailing WHERE after SET, not as
            // "WHEN MATCHED AND <condition> THEN" (which raises ORA-02000 "missing THEN keyword").
            Where = (inserted, excluded) => excluded.Price > inserted.Price,
        };

        var sql = provider.SqlDialect.BuildMoveDataSql<TestEntity>(
            context,
            tableInfo,
            "source_temp",
            insertedColumns,
            [],
            new OracleBulkInsertOptions(),
            onConflict);

        sql.Should().Contain("WHEN MATCHED THEN UPDATE SET");
        sql.Should().NotContain("WHEN MATCHED AND");
        // The condition is emitted as a trailing WHERE clause of the update.
        System.Text.RegularExpressions.Regex
            .IsMatch(sql, @"UPDATE\s+SET[\s\S]*?WHERE")
            .Should().BeTrue("the update condition must be a trailing WHERE clause");
    }
}



