using FluentAssertions;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using PhenX.EntityFrameworkCore.BulkInsert.Abstractions;
using PhenX.EntityFrameworkCore.BulkInsert.Metadata;
using PhenX.EntityFrameworkCore.BulkInsert.Options;
using PhenX.EntityFrameworkCore.BulkInsert.Sqlite;
using PhenX.EntityFrameworkCore.BulkInsert.Tests.DbContext;

using Xunit;

namespace PhenX.EntityFrameworkCore.BulkInsert.Tests.Tests.Merge;

/// <summary>
/// Container-free unit tests asserting the SQL generated by the dialect for conflict update expressions.
/// </summary>
public class SqliteMergeSqlTests
{
    private static TestDbContextSqlite CreateContext() => new()
    {
        ConfigureOptions = options => options
            .UseSqlite("Data Source=:memory:")
            .UseBulkInsertSqlite()
    };

    private static string BuildUpdateSql(OnConflictOptions<TestEntity> onConflict)
    {
        using var context = CreateContext();

        var provider = context.GetService<IBulkInsertProvider>();
        var tableInfo = new MetadataProvider().GetTableInfo<TestEntity>(context);
        var insertedColumns = tableInfo.GetColumns(includeGenerated: false);

        return provider.SqlDialect.BuildMoveDataSql<TestEntity>(
            context,
            tableInfo,
            "source_temp",
            insertedColumns,
            [],
            new BulkInsertOptions(),
            onConflict);
    }

    [Fact]
    public void BuildMoveDataSql_ConflictUpdate_EvaluatesParameterIndependentMethodCall()
    {
        var identifier = Guid.NewGuid();

        var onConflict = new OnConflictOptions<TestEntity>
        {
            Match = e => new { e.Name },
            // Guid.NewGuid() does not reference the entity parameters, so it must be evaluated
            // locally and emitted as a literal rather than translated to SQL.
            Update = (inserted, excluded) => new TestEntity { Identifier = identifier },
        };

        var sql = BuildUpdateSql(onConflict);

        sql.Should().Contain($"'{identifier}'");
    }

    [Fact]
    public void BuildMoveDataSql_ConflictUpdate_EvaluatesCapturedLocalVariable()
    {
        const decimal newPrice = 42.5m;

        var onConflict = new OnConflictOptions<TestEntity>
        {
            Match = e => new { e.Name },
            Update = (inserted, excluded) => new TestEntity { Price = newPrice },
        };

        var sql = BuildUpdateSql(onConflict);

        sql.Should().Contain("42.5");
    }
}


